### ISSUE TITLE
Request for adding the hyperC RTOS 

### ISSUE THREAD

**Issue by socware-net** [osrtos/osrtos#1]
web: https://socware.net/?p=525
code: https://github.com/socware-net/hyperCOS-evaluate
license: others

**Comment by yplam** [comment]
Hi @socware-net, what's the difference between https://github.com/socware-net/hyperCOS-evaluate and https://github.com/ibanezchen/hyperCOS-evaluate? 

It seems https://github.com/ibanezchen/hyperCOS-evaluate is more up to date.

**Comment by socware-net** [comment]
Thanks for the quick response. We'll maintain the https://github.com/socware-net/hyperCOS-evaluate and will deprecate https://github.com/ibanezchen/hyperCOS-evaluate soon.
