### ISSUE TITLE
apache nuttx is on version 12.something, website says 10.something

### ISSUE THREAD

**Issue by xgpt** [osrtos/osrtos#22]

**Comment by xgpt** [comment]
nuttx-10.1.0 per https://www.osrtos.com
nuts-12.1.0 per https://github.com/apache/nuttx/tags

**Comment by yplam** [comment]
Fixed [bde5a03](https://github.com/osrtos/osrtos/commit/bde5a03c07e9b5739beb2e84bad7eec5dcff00fb)
